
QM3_2_DATASET = 'QM3.2'
PPD1_1_DATASET = 'PPD1.1'

PACK_CODE_TO_ACTION_TYPE = {
    'P_IC_ICL1': 'ICL1E',
    'P_IC_ICL2B': 'ICL2W',
    'P_IC_ICL4': 'ICL4N',
    'P_IC_H1': 'ICHHQE',
    'P_IC_H2': 'ICHHQW',
    'P_IC_H4': 'ICHHQN'
}
