from config import Config

QM_SUPPLIER = 'QM'
PPO_SUPPLIER = 'PPO'

QM3_2_DATASET = 'QM3.2'
PPD1_1_DATASET = 'PPD1.1'

PACK_CODE_TO_SFTP_DIRECTORY = {
    'P_IC_ICL1': Config.SFTP_PPO_DIRECTORY,
    'P_IC_ICL2B': Config.SFTP_PPO_DIRECTORY,
    'P_IC_ICL4': Config.SFTP_PPO_DIRECTORY,
    'P_IC_H1': Config.SFTP_QM_DIRECTORY,
    'P_IC_H2': Config.SFTP_QM_DIRECTORY,
    'P_IC_H4': Config.SFTP_QM_DIRECTORY
}

PACK_CODE_TO_DATASET = {
    'P_IC_ICL1': PPD1_1_DATASET,
    'P_IC_ICL2B': PPD1_1_DATASET,
    'P_IC_ICL4': PPD1_1_DATASET,
    'P_IC_H1': QM3_2_DATASET,
    'P_IC_H2': QM3_2_DATASET,
    'P_IC_H4': QM3_2_DATASET
}

PRINT_FILES_EXPECTED = {
    'P_IC_H1': Config.P_CI_H1_EXPECTED,
    'P_IC_H2': Config.P_CI_H2_EXPECTED,
    'P_IC_H4': Config.P_CI_H4_EXPECTED,
    'P_IC_ICL1': Config.P_CI_ICL1_EXPECTED,
    'P_IC_ICL2B': Config.P_CI_ICL2B_EXPECTED,
    'P_IC_ICL4': Config.P_CI_ICL4_EXPECTED
}
