platform: linux

image_resource:
  type: docker-image
  source:
    repository: eu.gcr.io/census-gcr/gcloud-kubectl

params:
  SERVICE_ACCOUNT_JSON:
  GCP_PROJECT_NAME:
  KUBERNETES_CLUSTER:
  PERFORMANCE_TESTS_IMAGE:
  CASE_PROCESSOR_REPLICAS:

inputs:
- name: performance-tests-repo

run:
  path: bash
  args:
    - -exc
    - |
      cat >~/gcloud-service-key.json <<EOL
      $SERVICE_ACCOUNT_JSON
      EOL

      # Use gcloud service account to configure kubectl
      gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      gcloud container clusters get-credentials ${KUBERNETES_CLUSTER} --zone europe-west2 --project ${GCP_PROJECT_NAME}

      export TEST_SCENARIO=`gsutil cat gs://census-rm-performance-sample-files/target-scenario-tag.txt`

      # THIS IS THE PUBSUB PERFORMANCE TEST SECTION
      if [ "$TEST_SCENARIO" == "\"@pubsub\"" ]; then
        kubectl scale deployment case-processor --replicas=0

        # Create an performance tests pod and run the performance tests in it
        # Env vars have to passed one by one as a --env flag each
        # The sleep is to give kubectl time to attach properly, otherwise the first few log lines are lost
        set +x
        kubectl run performance-tests -it --command --rm --quiet \
        --generator=run-pod/v1 \
        --image=${PERFORMANCE_TESTS_IMAGE} \
        --restart=Never \
        $(while read env; do echo --env=${env}; done < performance-tests-repo/kubernetes.env) \
        --env=SFTP_HOST=$(kubectl get secret sftp-ssh-credentials -o=jsonpath="{.data.host}" | base64 --decode) \
        --env=SFTP_USERNAME=$(kubectl get secret sftp-ssh-credentials -o=jsonpath="{.data.username}" | base64 --decode) \
        --env=SFTP_KEY=$(kubectl get secret sftp-ssh-credentials -o=jsonpath="{.data.private-key}") \
        --env=SFTP_PASSPHRASE=$(kubectl get secret sftp-ssh-credentials -o=jsonpath="{.data.passphrase}" | base64 --decode) \
        --env=SFTP_PPO_DIRECTORY=$(kubectl get configmap project-config -o=jsonpath="{.data.sftp-ppo-supplier-directory}") \
        --env=SFTP_QM_DIRECTORY=$(kubectl get configmap project-config -o=jsonpath="{.data.sftp-qm-supplier-directory}") \
        --env=RABBITMQ_USER=$(kubectl get secret rabbitmq -o=jsonpath="{.data.rabbitmq-username}" | base64 --decode) \
        --env=RABBITMQ_PASSWORD=$(kubectl get secret rabbitmq -o=jsonpath="{.data.rabbitmq-password}" | base64 --decode) \
        --env=RABBITMQ_MAN_PORT=15672 \
        --env=GOOGLE_SERVICE_ACCOUNT_JSON=$(kubectl get secret pubsub-credentials -o=jsonpath="{.data['service-account-key\.json']}") \
        --env=GOOGLE_APPLICATION_CREDENTIALS="/home/performancetests/service-account-key.json" \
        -- /bin/bash -c "sleep 2; behave pubsub_features --tags=${TEST_SCENARIO} --no-capture"

        kubectl scale deployment case-processor --replicas=$CASE_PROCESSOR_REPLICAS
        kubectl rollout status deploy case-processor --watch=true --timeout=200s
      fi

      # Create an performance tests pod and run the performance tests in it
      # Env vars have to passed one by one as a --env flag each
      # The sleep is to give kubectl time to attach properly, otherwise the first few log lines are lost
      set +x
      kubectl run performance-tests -it --command --rm --quiet \
      --generator=run-pod/v1 \
      --image=${PERFORMANCE_TESTS_IMAGE} \
      --restart=Never \
      $(while read env; do echo --env=${env}; done < performance-tests-repo/kubernetes.env) \
      --env=SFTP_HOST=$(kubectl get secret sftp-ssh-credentials -o=jsonpath="{.data.host}" | base64 --decode) \
      --env=SFTP_USERNAME=$(kubectl get secret sftp-ssh-credentials -o=jsonpath="{.data.username}" | base64 --decode) \
      --env=SFTP_KEY=$(kubectl get secret sftp-ssh-credentials -o=jsonpath="{.data.private-key}") \
      --env=SFTP_PASSPHRASE=$(kubectl get secret sftp-ssh-credentials -o=jsonpath="{.data.passphrase}" | base64 --decode) \
      --env=SFTP_PPO_DIRECTORY=$(kubectl get configmap project-config -o=jsonpath="{.data.sftp-ppo-supplier-directory}") \
      --env=SFTP_QM_DIRECTORY=$(kubectl get configmap project-config -o=jsonpath="{.data.sftp-qm-supplier-directory}") \
      --env=RABBITMQ_USER=$(kubectl get secret rabbitmq -o=jsonpath="{.data.rabbitmq-username}" | base64 --decode) \
      --env=RABBITMQ_PASSWORD=$(kubectl get secret rabbitmq -o=jsonpath="{.data.rabbitmq-password}" | base64 --decode) \
      --env=RABBITMQ_MAN_PORT=15672 \
      -- /bin/bash -c "sleep 2; behave features --tags=${TEST_SCENARIO} --no-capture"
