platform: linux
image_resource:
  type: docker-image
  source:
    repository: eu.gcr.io/census-gcr/gcloud-kubectl
params:
  SERVICE_ACCOUNT_JSON:
  KUBERNETES_CLUSTER:
  GCP_PROJECT_NAME:
inputs:
  - name: census-rm-kubernetes-dependencies-repo
    path: bash
    args:
      - -exc
      - |
        cat >~/gcloud-service-key.json <<EOL
        $SERVICE_ACCOUNT_JSON
        EOL
        # Use gcloud service account to configure kubectl
        gcloud auth activate-service-account --key-file ~/gcloud-service-key.json

        # Start Postgresql instance
        SQL_NAME=`gcloud sql instances list --format="value(name)"`
        echo $SQL_NAME
        gcloud sql instances patch $SQL_NAME --activation-policy ALWAYS

#      Let Terraform deal with scaling k8s node pools - uses the appropriate count from the TF variables